name: Run python.main

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  python-run:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python main.py
        env:
          PASS_GOOGLE_AUTHENTICATION: ${{ secrets.PASS_GOOGLE_AUTHENTICATION }}
          SENDER_GMAIL: ${{ vars.SENDER_GMAIL }}
          EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}